#!/usr/bin/env bash
# Builds service-audit-full.md: the whole assessment (agent instructions,
# all category files, report template) as a single file for attaching to
# web-based LLM chats. Run from anywhere; output lands in the repo root.
set -euo pipefail
cd "$(dirname "$0")/.."

out="service-audit-full.md"
version=$(sed -n 's/.*Spec version: \([0-9.]*\).*/\1/p' README.md | head -1)

if [[ -z "$version" ]]; then
  echo "error: could not find spec version in README.md" >&2
  exit 1
fi

version_files=(
  ASSESSMENT.md
  AGENT.md
  templates/report.md
  assessment/*.md
  coverage/[a-z]*.md
)

for f in "${version_files[@]}"; do
  if ! grep -Fq "$version" "$f"; then
    echo "error: $f does not contain spec version $version" >&2
    exit 1
  fi
done

{
  echo "<!-- Generated by scripts/build-bundle.sh from spec version ${version}. Do not edit directly. -->"
  echo ""
  echo "> This is the single-file bundle of the Software Project Maturity Assessment."
  echo "> All files the agent instructions below refer to (the seven category files and"
  echo "> the report template) are included in this document — no other files are needed."
  echo ""
  cat AGENT.md
  for f in assessment/0*.md; do
    echo ""
    echo "---"
    echo ""
    cat "$f"
  done
  echo ""
  echo "---"
  echo ""
  echo "# Report template"
  echo ""
  cat templates/report.md
} > "$out"

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines, spec version ${version})"
